#!/usr/bin/env sh

# === variables =============================================================
gaps="2"
gaps_inner="10"

normal_border_color="4c96a8"
focused_border_color="a3b95a"
preselect_border_color="98676a"

# === if disabling SIP ======================================================
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# csrutil enable --without debug --without fs

# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa

# === apps to ignore ========================================================
yabai -m rule --add app="R" manage=off
yabai -m rule --add app="^mpv$" sticky=on layer=above manage=off
yabai -m rule --add app="^Automator$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Console$" sticky=on layer=above manage=off
yabai -m rule --add app="^Adobe Photoshop 2020" sticky=on layer=above manage=off
yabai -m rule --add app="^LibreOffice" sticky=on layer=above manage=off
yabai -m rule --add app="^CleanMyMac" sticky=on layer=above manage=off
yabai -m rule --add app="^App Uninstaller$" sticky=on layer=above manage=off
yabai -m rule --add app="^Font Book$" sticky=on layer=above manage=off
yabai -m rule --add app="Photoshop" sticky=on layer=above manage=off
yabai -m rule --add app="^Keychain Access$" sticky=on layer=above manage=off
yabai -m rule --add app="^Bartender 4$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="Fantastical" manage=off
yabai -m rule --add app="Discord" sticky=on layer=above manage=off
yabai -m rule --add app="^Messages$" sticky=on layer=above manage=off
yabai -m rule --add app="^Netiquette$" sticky=on layer=above manage=off
yabai -m rule --add app="Bear" manage=off layer=above
yabai -m rule --add app="^iTerm2$" manage=on
yabai -m rule --add app="^DaisyDisk$" sticky=on layer=above manage=off
yabai -m rule --add app="KnockKnock" sticky=on layer=above manage=off
yabai -m rule --add app="Contacts" sticky=on layer=above manage=off
yabai -m rule --add app="^Canary Mail" sticky=on layer=above manage=off
yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^PDF Expert$" manage=off
yabai -m rule --add app="^Skim$" manage=off
yabai -m rule --add app="^Preview$" manage=off

# === global settings ========================================================
# Set the layout of the selected space
#   [bsp|stack|float]
yabai -m config layout bsp

# Override default layout for space 2 only
# yabai -m config --space 2 layout float

# When focusing a window, put the mouse at its center. (default: off)
yabai -m config mouse_follows_focus           off
# Automatically focus the window under the mouse. (off, autoraise, autofocus)
yabai -m config focus_follows_mouse           autoraise
# Specify which display a newly created window should be managed in.
#    default: The display in which the window is created (standard macOS behaviour).
#    focused: The display that has focus when the window is created.
#    cursor: The display that currently holds the mouse cursor.
yabai -m config window_origin_display         default
# Specify whether managed windows should become the first or second leaf-node
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement              second_child
# Floating windows are always on top (default: off)
#    System Integrity Protection must be partially disabled.
yabai -m config window_topmost                off

# Windows will keep their zoom-state through layout changes
yabai -m window_zoom_persist                  on

# Modify window shadows (default: on [on|off|float])
#    System Integrity Protection must be partially disabled.
yabai -m config window_shadow                 float

# Enable opacity for windows.
#    System Integrity Protection must be partially disabled.
yabai -m config window_opacity                on
# Opacity of the focused window.
#    System Integrity Protection must be partially disabled.
yabai -m config active_window_opacity         1.0
# Opacity of an unfocused window.
#    System Integrity Protection must be partially disabled.
yabai -m config normal_window_opacity         0.95
# Duration of transition between active / normal opacity.
#    System Integrity Protection must be partially disabled.
yabai -m config window_opacity_duration       0.2

# Duration of window frame animation.
#    If 0.0, the change in dimension is not animated.
#    Requires Screen Recording permissions.
#    System Integrity Protection must be partially disabled.
yabai -m config window_animation_duration    0.4
# Frame rate (expressed in frames per second) of window frame animation.
#    This setting does nothing if window_animation_duration is set to 0.0.
yabai -m config window_animation_frame_rate  120

# === limelight =============================================================
# Draw border for windows.
yabai -m config window_border               on
# Draw border in high resolution mode; for High Dots Per Inch ("Retina") displays.
#    HiDPI uses significantly more memory.
yabai -m config window_border_hidpi         on
# Width of window border.
#    If the given width is an odd number, it will be incremented by 1.
yabai -m config window_border_width         5
# Radius of window border
yabai -m config window_border_radius        12
# Blur border allowing it to act as a backdrop for transparent windows.
yabai -m config window_border_blur          off

# Color of the border of the focused window.
yabai -m config active_window_border_color  "0xE0${focused_border_color}"
# Color of the border of an unfocused window.
yabai -m config normal_window_border_color  "0x00${normal_border_color}"

# === other settings ========================================================
# Color of the window --insert message selection
yabai -m config insert_feedback_color  "0xE0${preselect_border_color}"
# Balance the window tree upon change, so that all windows occupy the same area
yabai -m config auto_balance                  off
# Specify the size distribution when a window is split
yabai -m config split_ratio                   0.50
# Specify how a window should be split.
#    vertical:   The window is split along the y-axis.
#    horizontal: The window is split along the x-axis.
#    auto:       The axis is determined based on width/height ratio.
yabai -m config split_type                    auto
# Keyboard modifier used for moving and resizing windows
#   [cmd|alt|shift|ctrl|fn]
yabai -m config mouse_modifier                fn
# Action performed when pressing mouse_modifier + button1
#   [move|resize]
yabai -m config mouse_action1                 move
# Action performed when pressing mouse_modifier + button2
#   [move|resize]
yabai -m config mouse_action2                 resize
# Action performed when a bsp-managed window is dropped
# in the center of some other bsp-managed window.
#   [swap|stack]
yabai -m config mouse_drop_action             swap

# === general space settings =================================================
# yabai -m config focused_border_skip_floating  1
# yabai -m config --space 3 layout             float

# === appearance =============================================================
# Padding added at the upper side of the selected space
yabai -m config top_padding                     "${gaps}"
# Padding added at the lower side of the selected space
yabai -m config bottom_padding                  "${gaps}"
# Padding added at the left side of the selected space
yabai -m config left_padding                    "${gaps}"
# Padding added at the right side of the selected space
yabai -m config right_padding                   "${gaps}"
# Size of the gap that separates windows for the selected space
yabai -m config window_gap                      "${gaps_inner}"

# === statusbar =============================================================
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X

# https://github.com/felixhageloh/uebersicht
#
# Add 20 padding to the top and 0 padding to the bottom of
#   every space located on the main display
# yabai -m config external_bar main:20:0

# Add 20 padding to the top and bottom of
#   all spaces regardless of the display it belongs to
# yabai -m config external_bar all:20:20

# yabai -m config                                 \
#     split_ratio                  0.50           \
#     split_type                   auto           \
#     auto_balance                 off            \
#     top_padding                  12             \
#     bottom_padding               12             \
#     left_padding                 12             \
#     right_padding                12             \
#     window_gap                   06             \

# focus on next window when closing
# yabai -m signal --add event=window_destroyed action="bash "$HOME/mybin/yabai/winfocus.sh""
