#!/usr/bin/env sh
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# csrutil enable --without debug --without fs

# apps to ignore
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Adobe Photoshop 2020" sticky=on layer=above manage=off
yabai -m rule --add app="^LibreOffice" sticky=on layer=above manage=off
yabai -m rule --add app="^CleanMyMac" sticky=on layer=above manage=off
yabai -m rule --add app="^App Uninstaller$" sticky=on layer=above manage=off
yabai -m rule --add app="^Font Book$" sticky=on layer=above manage=off
yabai -m rule --add app="Photoshop" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="Fantastical" manage=off
yabai -m rule --add app="Discord" sticky=on layer=above manage=off
yabai -m rule --add app="^Messages$" sticky=on layer=above manage=off
yabai -m rule --add app=R manage=off
yabai -m rule --add app=Bear manage=off layer=above
yabai -m rule --add app="^iTerm2$" manage=on
yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^console$" manage=off

# global settings
# yabai -m config focus_follows_mouse         autoraise
# yabai -m config focus_follows_mouse         on
yabai -m config window_placement              second_child
yabai -m config window_topmost                off
# yabai -m config window_shadow                float
yabai -m config window_opacity                off
yabai -m config window_opacity_duration       0.00
yabai -m config active_window_opacity         1.0
# yabai -m config normal_window_opacity        0.97

# limelight is separate
yabai -m config window_border                 off
killall limelight &> /dev/null && (limelight &> /dev/null &)

## some other settings
yabai -m config auto_balance                  off
yabai -m config split_ratio                   0.50
yabai -m config mouse_modifier                ctrl
yabai -m config mouse_action1                 move
yabai -m config mouse_action2                 resize

# general space settings
# yabai -m config focused_border_skip_floating  1
# yabai -m config --space 3 layout             float

## Change how yabai looks
yabai -m config layout                          bsp
yabai -m config top_padding                     2
yabai -m config bottom_padding                  2
yabai -m config left_padding                    2
yabai -m config right_padding                   2
yabai -m config window_gap                      10

# focus on next window when closing
yabai -m signal --add event=window_destroyed action="bash "$HOME/mybin/winfocus-exit""

echo "yabai configuration loaded.."
