#!/usr/bin/env zsh

setopt extendedglob

set -e

print -n Filtering new messages

## Poor man's progress bar. adjust for number of steps
STEPS=30
print -n '   ['
local n; for n ( $(seq $STEPS) ) { print -n '.' }

print -n ']\b'

for n ( $(seq $STEPS) ) { print -n '\b' }

## Folder-based sorting (ignoring tag:new)
print -n j
notmuch tag -new -inbox +junk 'folder:"/.*Junk.*/"'
notmuch tag -new -inbox +junk 'folder:"/.*Spam.*/"'

# already archived - no longer unread or inbox
print -n a
notmuch tag +archived -new -unread -inbox 'folder:"/.*Archive.*/"'
# notmuch tag -new -unread -inbox "folder:/burnsac@me.com/Archive/"
# notmuch tag -new -unread -inbox "folder:/burnsppl@gmail.com/Archive/"
# notmuch tag -new -unread -inbox "folder:/lmb@lmburns.com/Archive/"
# notmuch tag -new -unread -inbox "folder:/lucas@lmburns.com/Archive/"

# == Services ============================================================= [[[
print -n 'g('
notmuch tag +github tag:new '(from:notifications@github.com)'
# Mentions us, better have a look
print -n p
notmuch tag -new +inbox +personal tag:new '(tag:github @lmburns)'
# Some of the projects we carea bout
print -n c
notmuch tag -new +inbox +project1 tag:new '(tag:github project1)'
print -n t
notmuch tag -new +inbox +project2 tag:new '(tag:github project2)'
print -n b
notmuch tag -new +inbox +project3 tag:new '(tag:github project3)'
print -n u
# rest of GitHub messages are for other projects and stay out of inbox
notmuch tag -new tag:new '(tag:github)'
## end GitHub
print -n ')'

# mailling lists
notmuch tag  -new +inbox +zsh +maillist tag:new 'to:@zsh.org'
notmuch tag  -new +inbox +notmuch +maillist tag:new and to:notmuch@notmuchmail.org

# we should look at right away
print -n e
notmuch tag -new +inbox +flagged +eu tag:new folder:/INBOX/ from:Accredo@orders.accredo.com from:postmaster@mac.com from:expiry@letsencrypt.org from:root@lmburns.com from:burnsac@me.com from:lmb@lmburns.com from:@sharefoodbringhope.org

notmuch tag -new +inbox +eu +burrell tag:new '(from:@burrellcenter.com *burrell*)'

# notmuch tag +rss from:lmb@lmburns.com and not tag:zsh

# individual emails
print -n 0
notmuch tag +apple to:burnsac at me.com and not tag:apple
notmuch tag +xyz to:lucas at lmburns.com and not tag:xyz
notmuch tag +xyz to:lmb at lmburns.com and not tag:xyz
notmuch tag +gmail to:burnsppl at gmail.com and not tag:gmail
print -n X

# Notification from project1's issue tracker and chat systems
# not really personal even though they are sent to:me@example.com
# print -n b
# notmuch tag -new +inbox +project1 tag:new from:notifications@tasks.example.com from:noreply@example.com from:chat.example.org
# ]]]

# To/Cc one of my addresses
print -n p
notmuch tag -new +inbox +personal tag:new '(to:Burns OR to:burnsac@me.com OR to:lucas@lmburns.com OR to:Lucas OR to:lmb@lmburns.com)'

# Might not be personal, but it mentions our uniquish name inside.
# Flag, but continue processing
print -n s
notmuch tag +inbox +personal tag:new '(Burns OR Lucas Burns)'

# other general emails
print -n g
notmuch tag -new +general tag:new 'to:@general'
# private@ for any other list go to INBOX
print -n P
notmuch tag +inbox +private tag:new 'to:private@'
# Flag anything with "project1"
print -n 1
notmuch tag -new +failed 'from:Mail Delivery System'
print -n t

# == All mail sent from me =================================================
print -n x
notmuch tag +sent from:burnsac@me.com and not tag:sent
print -n x
notmuch tag +sent from:lucas@lmburns.com and not tag:sent
print -n x
notmuch tag +sent from:lmb@lmburns.com and not tag:sent
print -n x
notmuch tag +sent from:burnsppl@gmail.com and not tag:sent
print -n 0


# **Threads to watch**
# We sent something
print -n w
notmuch tag +watch -new tag:new 'folder:/.*Sent.*/'
# Boss is involved
print -n B
notmuch tag +watch +inbox +boss tag:new '(from:boss@example.com OR to:boss@example.com OR cc:boss@example.com)'
# Look for new message in watched threads.
# Previously flagged once also count (we intended to reply but didn't)
print -n W
notmuch search --output=threads tag:watch OR tag:replied OR tag:flagged  | xargs notmuch tag +inbox +watch -new tag:new
##


notmuch tag +receipts 'folder:/.*eceipts.*/'
notmuch tag +convo 'folder:/.*onversation.*/'

## Undo potential false INBOX positives from ourself
# (keep the other tags like watch)
print -n -
notmuch tag -inbox -new tag:inbox from:lucas@lmburns.com from:burnsac@me.com from:lmb@lmburns.com
notmuch tag -flagged tag:flagged from:burnsac@me.com

# Anything else is still in inbox, but marked as unsorted
print -n i
notmuch tag +inbox +unsorted -new tag:new folder:/INBOX/ folder:/Archive/
# notmuch tag +inbox +unsorted -new tag:new "folder:burnsac@me.com/INBOX"
# notmuch tag +inbox +unsorted -new tag:new "folder:burnsppl@gmail.com/INBOX"
# notmuch tag +inbox +unsorted -new tag:new "folder:lucas@lmburns.com/INBOX"
# notmuch tag +inbox +unsorted -new tag:new "folder:lmb@lmburns.com/INBOX"

# the rest (other accounts and folders) are just unsorted
print -n u
notmuch tag +unsorted -new tag:new

# Tip: To sort unsorted again after updating these rules, do:
#    notmuch tag -unsorted +new tag:unsorted
#    notmuch tag -github +new tag:github

print ']'
