.TH jupview 1 jupyter
.SH NAME
jupview - preview jupyter notebooks in the terminal
.SH SYNOPSIS
\fBjupview\fR \fI[OPTIONS]\fR \fI[FILE...]\fR
.SH DESCRIPTION
\fBjupview\fR provides a way to view a rendered jupyter notebook in the terminal
using \fBbat(1)\fR. This is able to be used as a previewer with terminal file managers
like \fBlf(1)\fR, \fBranger(1)\fR, and (possibly) \fBnnn(1)\fR by default with no parameters given.
.SH OPTIONS
.HP
\fB\-P\fR, \fB\-\-pager\fR
.IP
view the \fI.ipynb\fR file in \fBbat\fR instead of stdout
.HP
\fB\-I\fR, \fB\-\-no\-input\fR
.IP
clear the input cells of the \fI.ipynb\fR file before previewing
.HP
\fB\-p\fR, \fB\-\-no\-prompt\fR
.IP
clear the input and output prompt markers that are denoted by 'In[1]' and 'Out[1]' respectively
.HP
\fB\-O\fR, \fB\-\-clear\-output\fR
.IP
clear the output cells of the \fI.ipynb\fR file before previewing
.HP
\fB\-t\fR, \fB\-\-theme\fR <theme>
.IP
specify syntax highlighting theme for \fBbat(1)\fR to use for writing to stdout or the pager
.SH DEPENDENCIES
.TP
\fB\- jupyter nbconvert(1)\fR
used for converting \fI.ipynb\fR file to HTML
.TP
\fB\- w3m(1)\fR
used for viewing the converted HTML file
.TP
\fB\- bat(1)\fR
used for syntax highlighting the output
.SH TERMINAL FILE MANAGERS
.HP
\fBlf\fR and \fBranger\fR
.IP
In your \fIscope.sh\fR or file you have set as a previewer
.PP
#!/bin/bash

handle_extensions() {
  case "${1}" in
    *.ipynb) jupview "${1}";;
  esac
}
.SH DETAILS
If you have issues, you are invited to open a pull request on Github <https://github.com/lmburns/dotfiles> or Gitlab <https://gitlab.com/lmburns/dotfiles> pages.
.SH AUTHORS
Written by Lucas Burns <lucas@burnsac.xyz> in 2020.
.SH LICENSE
GPLv3
.SH SEE ALSO
.BR jupyter (1),
.BR jupyter\ nbconvert (1)
.BR bat (1),
.BR lf (1),
.BR ranger (1)
.BR nnn (1),
.BR w3m (1),
