description = "XDG_CONFIG_HOME dir"

# Directories to index.
dirs = [
  "~/.config/",
]

skip = "Dirs"

# Set to true if you want skip symbolic links
ignore_symlinks = true

# Set to true if you want to ignore hidden files and directories
ignore_hidden = false

# Set to true to read .gitignore files and ignore matching files
gitignore = false
