#!/usr/bin/env bash

# desc: backup packages from brew, cargo, gem, go, npm, pip

BREW_FILE="brew_$(date +'%Y%m%d')"
CARGO_FILE="cargo_$(date +'%Y%m%d')"
GEM_FILE="gem_$(date +'%Y%m%d')"
GO_FILE="go_$(date +'%Y%m%d')"
NPM_FILE="npm_$(date +'%Y%m%d')"
PIP_FILE="pip_$(date +'%Y%m%d')"

DIR="$HOME/backup/packages"

mkdir -p "$DIR"

brew bundle dump --file="${DIR}/${BREW_FILE}" >/dev/null 2>&1
ls "${HOME}/.cargo/bin" | rg "^(cargo|rust)" -v > "${DIR}/${CARGO_FILE}"
gem list > "${DIR}/${GEM_FILE}"
ls "${HOME}/go/bin" > "${DIR}/${GO_FILE}"
npm list -g --depth=0 > "${DIR}/${NPM_FILE}"
pip list > "${DIR}/${PIP_FILE}"

ln -sf "${DIR}/${BREW_FILE}" "${XDG_CONFIG_HOME}/packages/brew_pkgs"
ln -sf "${DIR}/${CARGO_FILE}" "${XDG_CONFIG_HOME}/packages/cargo_pkgs"
ln -sf "${DIR}/${GEM_FILE}" "${XDG_CONFIG_HOME}/packages/gem_pkgs"
ln -sf "${DIR}/${GO_FILE}" "${XDG_CONFIG_HOME}/packages/go_pkgs"
ln -sf "${DIR}/${NPM_FILE}" "${XDG_CONFIG_HOME}/packages/npm_pkgs"
ln -sf "${DIR}/${PIP_FILE}" "${XDG_CONFIG_HOME}/packages/pip_pkgs"

dotbare add "${XDG_CONFIG_HOME}/packages/brew_pkgs"
dotbare add "${XDG_CONFIG_HOME}/packages/cargo_pkgs"
dotbare add "${XDG_CONFIG_HOME}/packages/gem_pkgs"
dotbare add "${XDG_CONFIG_HOME}/packages/go_pkgs"
dotbare add "${XDG_CONFIG_HOME}/packages/npm_pkgs"
dotbare add "${XDG_CONFIG_HOME}/packages/pip_pkgs"
