#!/usr/bin/env bash

# Desc: list all installed apps & dependencies

brew list -1 --formula \
  | while read cask;  do
      echo -ne "\x1B[1;34m $cask \x1B[0m"
      brew uses $cask --installed \
        | awk '{printf(" %s ", $0)}'; echo ""
    done
