#!/usr/bin/env zsh

# desc: send a notification of cryptocurrency prices

local file
local -a files output
output=()
files=( $XDG_CACHE_HOME/crypto/* )

for file in "${files[@]}"; do
  [[ "${file:t}" != "time" ]] && output+=( "${(f)"$(<$file)"}" )
done

output="${(F)output[@]}"
timef="${(f)"$(<$XDG_CACHE_HOME/crypto/time)"}"
# terminal-notifier -title "Crypto Prices" -message "$output"
osascript -e "display notification \"$output\" with title \"Crypto - $timef\""
