#!/bin/sh

# desc: fzf trash-restore

file="$(trash-list \
  | rg --color=never "$(pwd)" \
  | fzf --delimiter / --with-nth 1,-1 \
  | awk '{print $3}' \
)"

[ -n "$file" ] && yes 0 | trash-restore "$file" || exit 1
