#!/usr/bin/env zsh

# desc: git clone from clipboard

setopt extendedglob

zparseopts -D -A opts g -ghq

if (( ${+opts[-g]} + ${+opts[--ghq]} )) {
  ghq get "$(pbpaste)"
} else {
  git clone "$(pbpaste)"
}
