#!/usr/bin/env zsh

# Desc: git clone from clipboar or name/repo

setopt extendedglob

zparseopts -D -A opts g -ghq

if (( ${+opts[-g]} + ${+opts[--ghq]} )) {
  ghq get "$(pbpaste)"
} elif [[ "$(pbpaste)" =~ https:// ]] {
  git clone "$(pbpaste)"
} elif (( $# > 0 )) {
  gh repo clone "$@"
}
