#!/bin/sh

set -eu

readonly EX_USAGE=64
readonly EX_NOINPUT=66

usage() {
    echo "usage: $(basename "$0") <notebook>"
}

if [ $# -ne 1 ]; then
    usage
    exit $EX_USAGE
fi

if [ "$1" = -h ] || [ "$1" = --help ]; then
    usage
    exit
fi

if [ ! -f "$1" ]; then
    echo "$(basename "$0"): $1: No such file"
    exit $EX_NOINPUT
fi


jupyter nbconvert --stdout --to html "$1" 2>/dev/null | w3m -dump -T text/html | bat -Pf --theme gruvbox --style auto --language python

# base=$(basename -s .ipynb $1)
# temp="/tmp/$base.html"
# jupyter nbconvert --output-dir="/tmp/" --to html "$1" >/dev/null 2>&1
# w3m -dump "${temp}" && rm "${temp}"
