#!/bin/sh

manual=$(apropos . 2>/dev/null | \
    cut -d '-' -f 1 | \
    awk -F ', ' '{for(i=1;i<=NF;++i)if($i!="")printf("%s\n",$i)}' | \
    rg -v '[:!@#\$%&\*\.]' | \
    fzf --preview-window=right \
        --preview 'echo {1} | sed -e "s/([^()]*)//g" | xargs -I{S} man -Pcat {S} {2} 2>/dev/null' | \
    sed -e 's/([^()]*)//g')

[ -z $manual ] && exit 0
man $manual
