#!/bin/sh

# Desc: count mail with mutt

/usr/local/bin/mw -Y

# Needed for herbe notifications
export HOME=$HOME
# export DISPLAY=:0
# export XAUTHORITY="${HOME}/.Xauthority"

prefix="~/.local/share/mail"

# Loop through every account in ~/.mail
for account in "$prefix"*; do
    # Find all unread mail whose file is newer that the last time this script was run and count them
    newcount=$(find "$account"/INBOX/new -type f -newer ~/.config/neomutt/.mailsynclast 2> /dev/null | wc -l)
    # Are there any new unread mail?
    if [ "$newcount" -gt "0" ]; then
        # Send a notification
        /usr/local/bin/terminal-notifier -title "New Mail" -message "$newcount new mail in mailbox ${account#"$prefix"}" &
        nohup /usr/local/mybin/mn "$newcount new mail" >/dev/null &
    fi
done

# Update access time of a marker file
touch ~/.config/neomutt/.mailsynclast

# notmuch
#notmuch --config ~/.config/notmuch-config new
