#!/usr/bin/env bash

# generate a script in script directory
# set bin_dir (doesn't have to exist yet)

BIN_DIR="$HOME/mybin"

ANS=$(\
  dialog --title "Create a Script" \
        --clear \
        --cancel-label "Exit" \
        --inputbox 'Enter FILE name: ' 8 40 \
  3>&1 1>&2 2>&3 3>&- \
)

FILE=$BIN_DIR/$ANS

if [ -d "$BIN_DIR" ]; then
  if [ -e "$BIN_DIR/$ANS" ]; then
    $EDITOR "$FILE"
  else
    printf "#!/bin/sh\n\n\n" >> "$FILE"
    chmod +x "$FILE"
    if [ $EDITOR = "nvim" ]; then
      $EDITOR +3 "$FILE"
    else
      $EDITOR "$FILE"
    fi
  fi
fi
