#!/bin/sh

# desc: interactive process killer

ppgrep() {
  if [ "$1" = "" ]; then
    FZF=fzf
  else
    FZF="fzf $1"
  fi
  ps aux | eval "$FZF" | awk '{print $2}'
}

ppgrep "$@"

# ppkill() {
#   if [ "$1" = "^-" ]; then
#     QUERY=""
#   else
#     QUERY="$1"
#     [ $# -gt 0 ] && shift
#   fi
#   ppgrep "$QUERY" | xargs kill "$*"
# }

# ppkill
