#!/usr/bin/env bash

# Desc: add reminders from command line
# args: remind <title> <date> <time>

list="all_combined"

osascript - "$1" "$2" "$3" <<END
on run argv
    set stringedAll to date (item 2 of argv & " " & item 3 of argv)
    tell application "Reminders"
      tell list "$list"
        make new reminder with properties {name:item 1 of argv, due date:stringedAll}
      end tell
    end tell
end run
END
