#!/usr/bin/env bash

# desc: deletes .DS_Store and __MACOSX directories

set -e

PROGRAM='rmcrap'

die() {
    echo "$@"
    exit 1
}


cmd_usage() {
    cat <<-_EOF
    Usage:
      $PROGRAM [options]
        Remove '.DS_Store' file and '__MACOSX' directory recursively

    Options:
        -s, --show     Show tree diagram of what $PROGRAM is removing
        -c, --count    Show count of .DS_Store and __MACOSX removed

    Dependencies:
      'fd' is required and used as a find replacement
          brew install fd
      'as-tree' is used to view what $PROGRAM is removing
          cargo install -f --git https://github.com/jez/as-tree
_EOF
    exit 0
}

cmd_short_usage() {
    echo "Usage: rmcrap $COMMAND [--help,-h] [--show,-s]"
}

command_exists() {
    command -v "$1" >/dev/null 2>&1 || exit 1
}

count_cmd() {
  echo "$1 $(wc -l)"
}

cmd_rmcrap() {
    local opts fd=0 astree=0
    local show=0 count=0
    opts="$($GETOPT -o s,c -l show,count -- "$@")"
    local err=$?
    eval set -- "$opts"

    while true; do case "$1" in
            -s|--show) show=1; shift ;;
            -c|--count) count=1; shift ;;
            --) shift; break ;;
    esac done

    command_exists fd && fd=1
    command_exists as-tree && astree=1

    [[ $err -ne 0 ]] && die "$(cmd_short_usage)"

    if [[ $fd=1 ]]; then
      command_exists fd || die "fd is not in your \$PATH"
    elif [[ $astree=1 ]]; then
      command_exists as-tree || die "as-tree is not in your \$PATH"
    fi

    local rm_ds="fd -HI ^.DS_Store$ -tf"
    local rm_mac="fd -HI ^__MACOSX$ -td"

     if [[ $show = 1 ]] && [[ $count = 1 ]]; then
      $rm_ds | as-tree && \
        $rm_mac | as-tree && \
      $rm_ds | count_cmd ".DS_Store:" && \
        $rm_mac | count_cmd "__MACOSX:"
    elif [[ $show = 1 ]]; then
      $rm_ds | as-tree && \
        $rm_mac | as-tree
      echo 'done'
    elif [[ $count = 1 ]]; then
      $rm_ds | count_cmd ".DS_Store:" | as-tree && \
        $rm_mac | count_cmd "__MACOSX:" | as-tree
    fi

    $rm_ds -X rm && \
      $rm_mac -X rm
}


if [[ "$1" == "help" ]] || [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]; then
    cmd_usage
fi

cmd_rmcrap "$@"
