#!/bin/bash

# Desc: whitelist/blacklist apps with santactl

# sudo /bin/launchctl unload /Library/LaunchAgents/com.google.santa.plist
# sudo /bin/launchctl unload /Library/LaunchAgents/com.google.santad.plist
# sudo /bin/launchctl unload /Library/LaunchDaemons/com.google.santa.bundleservice.plist

typeset -a apps

apps=("Image Capture" "News" "Music" "QuickTime Player" "Siri" "Books" "Photo Booth" "Stickies" "TV" "Stocks" "Chess" "Maps")

case "$1" in
  blacklist)
    for app in "${apps[@]}"; do
      sudo santactl rule --blacklist --path /System/Applications/"$app".app
    done
    ;;
  remove)
    for app in "${apps[@]}"; do
      sudo santactl rule --remove --path /System/Applications/"$app".app
    done
    ;;
esac
