#!/usr/bin/env zsh

# Check zshmodules

# Parse the following command-line arguments as options

# Note on `-a`:
# Specify the name of where to save parsed options
# In this case, into an array named `option`

# Note on `-D`:
# if an option is detected, remove it from
# the positional parameters of the calling shell

zparseopts -D -a option \
  'c' '-create' \
  'd' '-daemon' \
  'e' '-edit' \
  'r' '-remote' \
  'q' '-quit' \
  'h' '-help'
case ${option[1]} in
  -c | --create) transmission-create ${@} ;;
  -d | --daemon) transmission-daemon ${@} ;;
  -e | --edit) transmission-edit ${@} ;;
  -r | --remote) transmission-remote ${@} ;;
  -q | --quit) transmission-remote --exit; exit 0 ;;
  -h | --help)
      print -rl -- "-c, --create transmission-create"
      print -rl -- "-d, --daemon transmission-daemon"
      print -rl -- "-e, --edit transmission-edit"
      print -rl -- "-r, --remote transmission-remote"
      print -rl -- "-q, --quite transmission-remote --exit"
      ;;
esac
