#!/usr/bin/env bash

# desc: updatedb for bash, macOS is sh which it is not

if [ "$(id -u)" = "0" ]; then
	rc=0
  export FCODES=$(sudo -u nobody /usr/bin/mktemp -t updatedb)
	/usr/sbin/chown nobody "$FCODES"
	tmpdb=$(su -fm nobody -c "$0") || rc=1
	if [ $rc = 0 ]; then
		install -m 0444 -o nobody -g wheel $FCODES /var/db/locate.database
	fi
	rm $FCODES
	exit $rc
fi
: ${LOCATE_CONFIG="/etc/locate.rc"}
if [ -f "$LOCATE_CONFIG" -a -r "$LOCATE_CONFIG" ]; then
       . $LOCATE_CONFIG
fi

# The directory containing locate subprograms
: ${LIBEXECDIR:=/usr/libexec}; export LIBEXECDIR
: ${TMPDIR:=/tmp}; export TMPDIR
if ! TMPDIR=$(/usr/bin/mktemp -d $TMPDIR/locateXXXXXXXXXX); then
	exit 1
fi

PATH=$LIBEXECDIR:/bin:/usr/bin:/usr/local/bin:$PATH; export PATH

# 6497475
set -o noglob

: ${mklocatedb:=locate.mklocatedb}      # make locate database program
: ${FCODES:=/var/db/locate.database}    # the database
: ${SEARCHPATHS:="/"}                   # directories to be put in the database
: ${PRUNEPATHS:="/private/tmp /private/var/folders /private/var/tmp */Backups.backupdb"} # unwanted directories
: ${FILESYSTEMS:="hfs ufs apfs"}        # allowed filesystems
: ${find:=find}

case X"$SEARCHPATHS" in
	X) echo "$0: empty variable SEARCHPATHS"; exit 1;; esac
case X"$FILESYSTEMS" in
	X) echo "$0: empty variable FILESYSTEMS"; exit 1;; esac

# Make a list a paths to exclude in the locate run
excludes="! (" or=""
for fstype in $FILESYSTEMS
do
	excludes="$excludes $or -fstype $fstype"
	or="-or"
done
excludes="$excludes ) -prune"

case X"$PRUNEPATHS" in
	X) ;;
	*) for path in $PRUNEPATHS
	do
		excludes="$excludes -or -path $path -prune"
	done;;
esac

# Ignore the target of firmlinks
while read firmlink; do
	excludes="$excludes -or -path $firmlink -prune"
done <<< "$(awk -F'\t' '{print "/System/Volumes/Data/" $2}' /usr/share/firmlinks)"

tmp=$TMPDIR/_updatedb$$
trap 'rm -f $tmp; rmdir $TMPDIR; exit' 0 1 2 3 5 10 15

# search locally
# echo $find $SEARCHPATHS $excludes -or -print && exit
if $find -s $SEARCHPATHS $excludes -or -print 2>/dev/null |
        $mklocatedb -presort > "$tmp"
then
  case X"$(fd "$tmp" -S -257b)" in
		X) cat $tmp > $FCODES;;
		*) echo "updatedb: locate database $tmp is empty"
		   exit 1
	esac
fi
