#!/bin/sh

# desc: open script in editor

Z="${ZDOTDIR}/functions/${*}"
fullp=$(which $*)
if file -b -L --mime-type "${fullp}" | grep -q "text/"; then
 "${EDITOR}" "${fullp}"
elif [ -f "$Z" ]; then
  "${EDITOR}" "${Z}"
else
 echo "${fullp} is not a text file"
fi
