[[snippets]]
  description = "broken symlink"
  command = "find . -type l ! -exec test -e {} \\; -print"
  output = ""

[[snippets]]
  description = "cpu/memory"
  command = "ps -A -o %cpu,%mem | awk '{ cpu += $1; mem += $2} END {print \"CPU: \"  cpu,\"MEM: \"  mem}'"
  output = ""

[[snippets]]
  description = "batt temp"
  command = "bc <<< \\\"scale=3; $(ioreg -r -n AppleSmartBattery | grep Temperature | cut -c23-)/100*1.8+32\\\""
  output = ""

[[snippets]]
  description = "run"
  command = "HOARD_LOG=debug just r -c $PWD/config.toml -h $PWD/out backup"
  output = ""

[[snippets]]
  description = "yaml"
  command = "HOARD_LOG=debug just r -c $PWD/config.yml -h $PWD/out backup"
  output = ""

[[snippets]]
  description = "json"
  command = "HOARD_LOG=debug just r -c $PWD/config.json -h $PWD/out backup"
  output = ""
